### ISSUE TITLE
error going from realignEcat -> avg_frames step

### ISSUE THREAD

**Issue by VeraKer** [cselenyi/solenabugs#10]
I have been having this error since always - apologies for the late reporting of it. I know from colleagues they have run into the same error.

I have a Corregistration block in my study layout consisting of 
- realignEcat7
- average_frames
- coregisterMR2PET

Each time when I run the block the worker can't continue to the second step without error. If I restart Solena then it does the average_frames step without problem.

Here is a screenshot of the error.
![Solena_error_avergae_frames](https://user-images.githubusercontent.com/46931135/63944201-69673f00-ca71-11e9-886c-ef45a73c6544.png)

The same error happens when I have several subjects queuing to do the avg_frames step: Subject 1 completes without a problem, Subject 2 will be "pending"  as long as subject 1 is still running. However, when subject 1 is done and subject 2 could start, it immediately fails with the above error message.

It seems like the avg_frames step can't handle being in "pending" state and starting as soon as it is its turn?

@cselenyi

**Comment by cselenyi** [comment]
@VeraKer this seems to be the same issue as #4 so should be addressed by the fix (workaround) planned to be implemented in the next worker version.

**Comment by cselenyi** [comment]
@VeraKer new worker should have addressed this, see #4. Please report your experience in that issue, I close this one :-)
