### ISSUE TITLE
freesurfMR processing I 

### ISSUE THREAD

**Issue by JoaBberg** [cselenyi/solenabugs#11]
how to transfrom manual quality check without interrupting solena worker?
![image](https://user-images.githubusercontent.com/57174873/67846499-9ed7e980-fb01-11e9-8edf-0607248154f5.png)

**Comment by cselenyi** [comment]
(@JoaBberg please could you point me to a specific subject with this issue so I can directly check this? Thanks!) Oh, ok, I got your email, thanks :-)

**Comment by cselenyi** [comment]
@JoaBberg the issue has been identified. The folder of the SPM12 MNI average image ('avg305T1.nii') was not in your MATLAB path. For now add it's folder to the MATLAB path (should be ..downloads\m-files\spm12\canonical). New versions of the worker will not need manual adding to the MATLAB path.
