### ISSUE TITLE
freesurfMR processing II

### ISSUE THREAD

**Issue by JoaBberg** [cselenyi/solenabugs#12]
Quality check of freesurfMR failed. How can you manually change threshold in freesurfMR wihtin solena?
![image](https://user-images.githubusercontent.com/57174873/67846709-f70eeb80-fb01-11e9-9173-8658b3af3b1c.png)

**Comment by cselenyi** [comment]
There was a bug in the subroutine handling the user input (in the SPM "interactive" window) for changing watershed threshold and other settings related to skull stripping. Now it's fixed. No worker modifications were needed for this one, should work for all (perhaps restart MATLAB).
