### ISSUE TITLE
avi2talxfm failed

### ISSUE THREAD

**Issue by martingarde** [cselenyi/solenabugs#22]
Posting log:

Fri Nov  6 13:43:58 UTC 2020
mri_nu_correct.mni done

 talairach_avi --i orig_nu.mgz --xfm transforms/talairach.auto.xfm 

talairach_avi log file is transforms/talairach_avi.log...
ERROR: avi2talxfm failed, see transforms/talairach_avi.log
Linux fsfsl_476818f0 4.19.130-boot2docker #1 SMP Mon Jun 29 23:52:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s KIH14001_test exited with ERRORS at Fri Nov  6 13:44:40 UTC 2020

For more details, see the log file /opt/freesurfer/subjects/KIH14001_test/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

There was an error running recon-all
Destroying process.
Error using freesurfMR (line 238)
There was some error running recon-all that could not be handled automatically.

----------------------------------------------------------------------------------------------------

Unfortunatly I am unaware of how to get hold of the talairach_avi.log file mentioned above

This error persists after deleting my work folder and starting over. Tried updating docker and virtualbox without avail. It does not seem to be dependent on the .nifti-file analyzed as it occurs on all subject currently.

Kind regards

Martin Gärde

**Comment by cselenyi** [comment]
@martingarde 
To find the logs mentioned: the subject's "freesurfer" folder is mapped into the Docker container, running freesurfer, into "/opt/freesurfer/subjects/subjectname", e.g. in your case "KIH14001_test". Accordingly, "transforms/talairach_avi.log" should be at  ".../subject_folder/freesurfer/mri/transforms/talairach_avi.log" and the "recon-all.log" should be at ".../subject_folder/freesurfer/scripts/recon-all.log". Please update the issue with relevant stuff from those logs.
