### ISSUE TITLE
fastcrc32 (??) error in one subject

### ISSUE THREAD

**Issue by EmmaRV** [cselenyi/solenabugs#3]
For one subject I get an error when creating the dicom catalogue / dicom conversions:

> Matrix index is out of range for deletion.
> 
> Error in fastcrc32 (line 139)
>             d(1:2)=[]; % first two are . and ..
> 
> Error in solena.executor/obtainChecksum (line 3071)
> 	                        [checksum(1,1),checksum(1,2),checksum(1,3),checksum(1,4)]=fastcrc32(fullfile(vbDir,val),[],lengthLimit);
>                             
> Error in solena.executor/handleRelayEvent (line 992)
>                                     command.inputs(i).checksum=obj.obtainChecksum(extendedInfo.actualInputs{i},crc32_length_limit);
>                                     % now we get the actual crc32
> 
> Error in solena.localrelay/workerChangeEvent (line 531)
>                     obj.Reserver.handleRelayEvent( obj, eventData ); % direct call back!!
> 
> Error in solena.localrelay>@(o,e)obj.workerChangeEvent(o,e) (line 390)
> 			set(hcb,'DelayedCallback',@(o,e)obj.workerChangeEvent(o,e));
> 
> Error in solena.localrelay>@(o,e)obj.workerChangeEvent(o,e) (line 390)
> 			set(hcb,'DelayedCallback',@(o,e)obj.workerChangeEvent(o,e));

I'm not sure if it's a Solena bug, since all the other subjects in the study don't give problems, but I also don't find something that could be wrong in the dicom files. When this error occurs, the worker won't be stopped and is waiting for input. A dicom catalogue is created, but the script doesn't finish to run all the files for the catalogue. Worker: solena_worker_201902111117

When realigning the petfile (realignEcat7) for this subject I get exactly the same error.

Any idea what the issue could be? @cselenyi  ?

**Comment by cselenyi** [comment]
It appears that you are somehow using an outdated version of Solena Manager (namely: the "executor.m" file). The "fastcrc32" line now is not at 3071 in solena.executor but at line 3075 or line 3080. Could you please check the you refer to the Solena toolbox on ecat7_nfs/downloads/m-files/solena? @EmmaRV

**Comment by EmmaRV** [comment]
@cselenyi Thank you, yes this folder was nearly on top of the MATLAB search paths (and moving it all the way up gave the same error).

**Comment by cselenyi** [comment]
@EmmaRV 
  Hm, something does not add up here! Could you point me to this study folder and subject so I can investigate it directly. Alternatively, we can try to debug it on your computer.

**Comment by EmmaRV** [comment]
@cselenyi I'll email the studypath. Interestingly the output is created for nearly all scripts, but the error occurs for every step in the pipeline for this subject (and I haven't seen this error at all when analyzing other subjects). From what I can see the output looks ok, but I have to run every line separately because it can't continue to a next line in one block. Since it gets stuck during the run I'm not sure if really all steps are followed well within the script.

**Comment by cselenyi** [comment]
@EmmaRV I've found the bug: the problem was that the subject's name "kron" coincides with the name of a MATLAB function and the bug itself seems to be in MATLAB itself: in such a case it reports "kron" as an "existing directory" (folder) within the "kron" folder (i.e. within the subject's own folder), which is not true. I have now made a workaround to fastcrc32 so it detects this false case and proceeds without problems. Please restart MATLAB and try again. I have processed the subject through the first 2 steps and it worked on my machine. Force reprocess and see how it goes on yours.

**Comment by EmmaRV** [comment]
Interesting catch! It can really be anything.. It works from my pc as well! Great, thank you! @cselenyi

**Comment by cselenyi** [comment]
Super! Closing it.
