### ISSUE TITLE
Realignment issue. Times switched.

### ISSUE THREAD

**Issue by ToveFrei** [cselenyi/solenabugs#5]
@cselenyi I have an issue with one subject in only one of my runs. In the realignment step the frames are mixed. In the picture you an see that 6 and 9 minutes are switched for instance. However, when opening the religned v-file in Vinci the frames are in the correct order. 
![nilsson_837_26e2_de5_realign_plot](https://user-images.githubusercontent.com/47004823/53495421-3b904600-3aa0-11e9-9fb9-c544b5270020.png)

The TACs that are created from this now look very odd as you would guess. However, I do get BPNDs that seem legit.

**Comment by cselenyi** [comment]
@ToveFrei 
  Thanks for the issue post. I have checked the original .v file and it is an error (or several errors) in the file itself on the frame timings. The frame images themselves are obviously in the correct order, hence the nice trace in the realignment plot but the timing info is wrong. This is not a Solena issue, the file must be fixed, perhaps by Göran. I am closing the issue.
