### ISSUE TITLE
Error using engWapi

### ISSUE THREAD

**Issue by EmmaRV** [cselenyi/solenabugs#8]
I tried to run some wapis, but it doesn't finish the script anymore due to an error. Some subjects I'd run before without problems (but I wanted to rerun them with a better choice of included frames). Would you have an idea what the issue could be @cselenyi?
I'm using engWapi on solena_worker_201903281122 and get the following error:

> 
![image](https://user-images.githubusercontent.com/14238465/56115868-b59f6000-5f64-11e9-82e6-4c90addc10e2.png)

And in MATLAB it shows:

> 
![image](https://user-images.githubusercontent.com/14238465/56115903-d071d480-5f64-11e9-826a-60e1f9876640.png)

Thank you in advance for your help!

**Comment by cselenyi** [comment]
@EmmaRV It looks like there was a bug that was introduced into `solena_worker_201903281122` with the supposedly better error reporting feature. I have (hopefully) fixed the bug. Please use worker: `solena_worker_201904151037` and see if the error still occurs.

**Comment by cselenyi** [comment]
@EmmaRV OOps, the new worker actually does NOT contain the intended fix of engWapi since it is a .p file which I forgot to recompile.. So I am going to create yet a new worker version right away..!

**Comment by cselenyi** [comment]
Now there is a new worker: `solena_worker_201904151349` with the actual fix. Please try..

**Comment by EmmaRV** [comment]
@cselenyi I've run engWapi now with solena_worker_201904151349 but unfortunately it stops at about the same spot, now the error is as follows:

> Error executing command: PET:engWapi, parameters: pet1_realigned.v    1_kinfitresults.mat 16                  3                   1_wapist            13                  REFNAME             RefCBL              LIMS                0                   32                  TARGETMASKNAME      WB                  TARGETMASKPADDING   1                   INJTIME             FRAME1              
Error report:
Error using engWapi (line 188)
There was some error running engWapi on the server. Error message:
Undefined function 'eq' for input arguments of type 'cell'.
Error in engMatlab (line 46)

This is btw a different study (with different nr of frames) as the previous one is still running something with the older worker.

**Comment by cselenyi** [comment]
@EmmaRV thanks, this is actually progress, since the error reporting itself now works and so I see that there was also a bug in the engMatlab process running on the server itself. I have now fixed that bug (hopefully). There was no need to change the worker so you could just give it another try and let's see what happens!

**Comment by EmmaRV** [comment]
@cselenyi Ah good, the error was in a different line nr in engWapi indeed. It's improving again, nearly there I think. After it moves all the tmp files, I get the following error:

> Retrieving WAPI image from server...
Error executing command: PET:engWapi, parameters: pet2_realigned.v    2_kinfitresults.mat 16                  3                   2_wapist            13                  REFNAME             RefCBL              LIMS                0                   32                  TARGETMASKNAME      WB                  TARGETMASKPADDING   2                   INJTIME             FRAME1              
Error report:
Error using sprintf
Function is not defined for 'cell' inputs.

Error in engWapi (line 198)

**Comment by cselenyi** [comment]
@EmmaRV Yet another attempt to fix the issue :-) Please try `solena_worker_201904161209`..

**Comment by EmmaRV** [comment]
@cselenyi Yes it's working! Thank you so much!

**Comment by cselenyi** [comment]
Oh, great, finally! :-)
